<template>
	<div class="slideNav">
	<el-menu theme="dark">
		<el-submenu index='1'>
			<template slot='title'>公路项目</template>
			<el-tree :props='defaultProps' :data='data' class='vm_tree'>
			</el-tree>
		</el-submenu>
		<el-submenu index='2'>
			<template slot='title'>铁路项目</template>
			<el-tree :props='defaultProps' :data='data' class='vm_tree'>
			</el-tree>
		</el-submenu>
	</el-menu>
	</div>
</template>

<script type="text/javascript">
	export default{
		data:function(){
			return{
				data:[{
					label:'贵州省',
					children:[{
					label:'A公司',
					children:[{
						label:'地点A',
						children:[{
							label:'梁场A',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场B',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场C',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						}]
					},{
						label:'地点A',
						children:[{
							label:'梁场A',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场B',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场C',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						}]
					},{
						label:'地点A',
						children:[{
							label:'梁场A',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场B',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场C',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						}]
					}]
				},{
					label:'B公司',
					children:[{
						label:'地点A',
						children:[{
							label:'梁场A',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场B',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场C',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						}]
					},{
						label:'地点A',
						children:[{
							label:'梁场A',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场B',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场C',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						}]
					},{
						label:'地点A',
						children:[{
							label:'梁场A',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场B',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场C',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						}]
					}]
				},{
					label:'C公司',
					children:[{
						label:'地点A',
						children:[{
							label:'梁场A',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场B',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场C',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						}]
					},{
						label:'地点A',
						children:[{
							label:'梁场A',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场B',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场C',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						}]
					},{
						label:'地点A',
						children:[{
							label:'梁场A',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场B',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场C',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						}]
					}]
				}
					]
				},{
					label:'贵州省',
					children:[{
					label:'A公司',
					children:[{
						label:'地点A',
						children:[{
							label:'梁场A',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场B',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场C',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						}]
					},{
						label:'地点A',
						children:[{
							label:'梁场A',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场B',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场C',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						}]
					},{
						label:'地点A',
						children:[{
							label:'梁场A',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场B',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场C',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						}]
					}]
				},{
					label:'B公司',
					children:[{
						label:'地点A',
						children:[{
							label:'梁场A',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场B',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场C',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						}]
					},{
						label:'地点A',
						children:[{
							label:'梁场A',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场B',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场C',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						}]
					},{
						label:'地点A',
						children:[{
							label:'梁场A',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场B',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场C',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						}]
					}]
				},{
					label:'C公司',
					children:[{
						label:'地点A',
						children:[{
							label:'梁场A',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场B',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场C',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						}]
					},{
						label:'地点A',
						children:[{
							label:'梁场A',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场B',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场C',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						}]
					},{
						label:'地点A',
						children:[{
							label:'梁场A',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场B',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场C',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						}]
					}]
				}
					]
				},{
					label:'贵州省',
					children:[{
					label:'A公司',
					children:[{
						label:'地点A',
						children:[{
							label:'梁场A',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场B',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场C',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						}]
					},{
						label:'地点A',
						children:[{
							label:'梁场A',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场B',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场C',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						}]
					},{
						label:'地点A',
						children:[{
							label:'梁场A',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场B',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场C',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						}]
					}]
				},{
					label:'B公司',
					children:[{
						label:'地点A',
						children:[{
							label:'梁场A',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场B',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场C',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						}]
					},{
						label:'地点A',
						children:[{
							label:'梁场A',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场B',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场C',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						}]
					},{
						label:'地点A',
						children:[{
							label:'梁场A',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场B',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场C',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						}]
					}]
				},{
					label:'C公司',
					children:[{
						label:'地点A',
						children:[{
							label:'梁场A',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场B',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场C',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						}]
					},{
						label:'地点A',
						children:[{
							label:'梁场A',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场B',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场C',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						}]
					},{
						label:'地点A',
						children:[{
							label:'梁场A',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场B',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						},{
							label:'梁场C',
							children:[{
								label:'梁场地点A',
								label:'梁场地点B',
								label:'梁场地点C',
							},]
						}]
					}]
				}
					]
				}],
				defaultProps:{
					label:'label',
					children:'children'
				}
			}
	}
}
</script>

<style type="text/css">
	.slideNav{
		position: absolute;
		top: 70px;
		height: 100%;
		width: 300px;
		background-color: #324157;
	}
	.vm_tree{
		background-color: #324157;
		border: none;
		color:#fff;
	}
</style>